### ISSUE TITLE
Make sample compile and run and a little writeup for how to get started

### ISSUE THREAD

**Issue by einari** [dolittle-samples/Basic#3]

**Comment by jwillmer** [comment]
Did you intended to remove [`Web.csproj`](https://github.com/dolittle-samples/Basic/commit/96ce9374b605f7481b92bed9ae5fbb97692ce980#diff-48e8f0f223bb832cb9f6459bb698a22b)?

Because now the web project can not be loaded anymore.

**Comment by jwillmer** [comment]
Running it via `run` command of VS I get 
![run](https://user-images.githubusercontent.com/1503577/46861652-693b6200-ce13-11e8-8918-ce1c52b8e27a.png)


Using `node run.js` as described in the documentation I get:
![web](https://user-images.githubusercontent.com/1503577/46861679-7ce6c880-ce13-11e8-81ab-6bcd92fca4d7.png)

**Comment by jwillmer** [comment]
Works! 
![localhost_5000_ galaxy s5](https://user-images.githubusercontent.com/1503577/46868509-d7d6ea80-ce28-11e8-82fa-6c3c50530c42.png)

**Comment by einari** [comment]
Excellent - closing
